sudo: required
services:
  - docker

before_install:
  - docker build -t mitchelle93/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true mitchelle93/react-test npm test

after_success:
  - docker build -t mitchelle93/multi-client:latest ./client
  - docker build -t mitchelle93/multi-nginx:latest ./nginx
  - docker build -t mitchelle93/multi-server:latest ./server
  - docker build -t mitchelle93/multi-worker:latest ./worker

  # login to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take images and push them to docker hub
  - docker push mitchelle93/multi-client:latest
  - docker push mitchelle93/multi-nginx:latest
  - docker push mitchelle93/multi-server:latest
  - docker push mitchelle93/multi-worker:latest