sudo: required
services:
  - docker

before_install:
  - docker build -t mitchelle93/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true mitchelle93/react-test npm test

after_success:
  - docker build -t mitchelle93/multi-client ./client
  - docker build -t mitchelle93/multi-nginx ./nginx
  - docker build -t mitchelle93/multi-server ./server
  - docker build -t mitchelle93/multi-worker ./worker
